/**
 * tools/archmap-report.mjs
 *
 * Self-contained offline HTML architecture explorer renderer.
 * Dark minimalist Russian engineering interface.
 * Zero external assets, no CDN, offline-first.
 */

const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  }[c]));

/** Translate standard English phrases and findings safely into Russian */
const KIND_RU = {
  cycle: "Цикл зависимостей",
  size: "Размер файла",
  complexity: "Цикломатическая сложность",
  hub: "Узел зацепления (хаб)",
  orphan: "Изолированный файл",
  wrapper: "Тонкая обёртка",
  maintainability: "Индекс поддерживаемости",
  dead: "Мёртвый код",
};

const SEV_RU = {
  high: "важно",
  medium: "средне",
  low: "инфо",
};

const SYM_KIND_RU = {
  function: "функция",
  method: "метод",
  class: "класс",
  constructor: "конструктор",
  getter: "геттер",
  setter: "сеттер",
  module: "модуль",
  type: "тип",
  interface: "интерфейс",
  trait: "трейт",
  constant: "константа",
};

const REASON_RU = {
  external: "Внешняя библиотека или системный рантайм",
  dynamic: "Динамический вызов (вызов параметра, свойство по ключу, возврат функции)",
  unresolved: "Неразрешённый идентификатор в контексте проекта",
  unsupported: "Конструкция вне возможностей статического анализа",
};

function ruPlural(n, one, few, many) {
  const abs = Math.abs(n) % 100;
  const d = abs % 10;
  if (abs > 10 && abs < 20) return many;
  if (d > 1 && d < 5) return few;
  if (d === 1) return one;
  return many;
}
function translateFindingText(text) {
  if (!text) return "";
  let s = String(text);
  // Replace standard phrases if generated by older English scanner
  s = s.replace(/(\d+)\s+files form a dependency cycle/g, "$1 файлов образуют цикл взаимных зависимостей");
  s = s.replace(/Each one needs the other to compile, so they can only change together\..*$/g, "Каждый модуль зависит от другого; их невозможно изменять и компилировать изолированно. Источник каскадных поломок.");
  s = s.replace(/Break the loop at its weakest link: extract the shared piece into a third module both can import\./g, "Разорвите цикл в слабейшем звене: вынесите общий фрагмент в отдельный независимый модуль.");
  s = s.replace(/(\d+)\s+lines in one file/g, "$1 строк в одном файле");
  s = s.replace(/(\d+)\s+lines/g, "$1 строк");
  s = s.replace(/Long files hide their own structure; nobody reads them end to end\./g, "Крупные файлы скрывают свою структуру и затрудняют анализ архитектуры.");
  s = s.replace(/Split by responsibility — not by line count\. Find the two things it does and separate them\./g, "Разделите файл по зонам ответственности, выделив самостоятельные подсистемы.");
  s = s.replace(/Large enough that its responsibilities are probably mixed\./g, "Объём файла указывает на возможное смешение нескольких обязанностей.");
  s = s.replace(/Check whether two distinct concerns live here\./g, "Проверьте, не выполняет ли файл несколько не связанных задач.");
  s = s.replace(/complexity\s+(\d+)\s+\((\d+)\s+branches\)/g, "сложность $1 ($2 точек ветвления)");
  s = s.replace(/Every branch is a case someone must hold in their head, and a path tests can miss\./g, "Каждое ветвление увеличивает число комбинаций состояний и риск упустить пограничный сценарий в тестах.");
  s = s.replace(/Extract the deepest nested branch into a named function\./g, "Вынесите вложенные ветвления и условия в отдельные функции.");
  s = s.replace(/imported by\s+(\d+)\s+files and\s+(\d+)\s+lines long/g, "импортируется $1 файлами при длине в $2 строк");
  s = s.replace(/Everything routes through it\. A change here has repo-wide blast radius, and it cannot be tested in isolation\./g, "Через модуль проходит слишком много потоков. Изменения здесь имеют максимальный радиус поражения.");
  s = s.replace(/Split it along the axis its importers actually use\./g, "Разделите модуль по интерфейсам, требуемым конкретным потребителям.");
  s = s.replace(/nothing imports it and it imports nothing/g, "файл никем не импортируется и ничего не импортирует");
  s = s.replace(/Either an entry point, or dead code nobody noticed\./g, "Либо точка входа, либо неиспользуемый изолированный код.");
  s = s.replace(/If nothing runs it, delete it\. Dead code costs reading time forever\./g, "Если файл не вызывается извне или тестов, удалите его.");
  s = s.replace(/a\s+(\d+)-line file with a single export/g, "файл из $1 строк с единственным экспортом");
  s = s.replace(/A pass-through adds a hop without hiding anything\..*$/g, "Сквозной прокси-модуль не инкапсулирует логику, а лишь удлиняет цепочку вызовов.");
  s = s.replace(/Inline it into its only consumer, or make it actually hide something\./g, "Встройте логику по месту вызова либо наделите модуль реальной ответственностью.");
  s = s.replace(/Maintainability Index is\s+(\d+)\/100/g, "Индекс поддерживаемости равен $1/100");
  s = s.replace(/Hard to read, test, or modify safely\..*$/g, "Код сложен для чтения, рефакторинга и покрытия тестами.");
  s = s.replace(/Simplify branches, split functions, and reduce cognitive load\./g, "Упростите ветвления, разбейте крупные функции и снизьте когнитивную нагрузку.");
  // Translate limitation taxonomy keywords if present
  s = s.replace(/\bdynamic\b/gi, "динамический");
  s = s.replace(/\bexternal\b/gi, "внешний");
  s = s.replace(/\bunresolved\b/gi, "неразрешённый");
  s = s.replace(/\bunsupported\b/gi, "неподдерживаемый");
  return s;
}

/** Layout for modules graph: layered topological sort */
function layoutModules(state) {
  const files = Object.keys(state.files || {});
  if (!files.length) {
    return { pos: new Map(), width: 600, height: 300, maxDepth: 0 };
  }
  const depth = new Map();
  const compute = (p, seen = new Set()) => {
    if (depth.has(p)) return depth.get(p);
    if (seen.has(p)) return 0;
    seen.add(p);
    const deps = (state.files[p] && state.files[p].deps) || [];
    const d = deps.length ? 1 + Math.max(0, ...deps.map((x) => compute(x, seen))) : 0;
    depth.set(p, d);
    return d;
  };
  for (const p of files) compute(p);

  const layers = new Map();
  for (const p of files) {
    const d = depth.get(p) || 0;
    if (!layers.has(d)) layers.set(d, []);
    layers.get(d).push(p);
  }
  const maxDepth = Math.max(0, ...[...layers.keys()]);
  const colW = 260, rowH = 42, padX = 40, padY = 50;
  const pos = new Map();
  const maxLayerRows = 24;
  let maxVirtualRows = 0;
  let totalCols = maxDepth + 1;
  let currentColOffset = 0;

  for (let d = maxDepth; d >= 0; d--) {
    const list = layers.get(d) || [];
    list.sort();
    const numSubCols = Math.max(1, Math.ceil(list.length / maxLayerRows));
    const effectiveRows = Math.min(list.length, maxLayerRows);
    maxVirtualRows = Math.max(maxVirtualRows, effectiveRows);
    list.forEach((p, i) => {
      const subCol = Math.floor(i / maxLayerRows);
      const subRow = i % maxLayerRows;
      pos.set(p, {
        x: padX + (currentColOffset + subCol) * colW,
        y: padY + subRow * rowH,
        depth: d,
      });
    });
    currentColOffset += numSubCols;
  }
  const width = Math.max(700, padX * 2 + currentColOffset * colW);
  const height = Math.max(400, padY + maxVirtualRows * rowH + 60);
  return { pos, width, height, maxDepth };
}

/** Build SCC map to accurately identify cycle membership */
function buildCycleMap(cycles) {
  const cycleMap = new Map();
  if (!Array.isArray(cycles)) return cycleMap;
  cycles.forEach((comp, idx) => {
    if (!Array.isArray(comp)) return;
    for (const node of comp) {
      if (!cycleMap.has(node)) cycleMap.set(node, new Set());
      cycleMap.get(node).add(idx);
    }
  });
  return cycleMap;
}

/** Pre-render SVG for initial module mode */
function renderModuleSvg(state, L) {
  const cycleMap = buildCycleMap(state.cycles);
  const nodeW = 200, nodeH = 26;
  const edges = [];
  const files = Object.entries(state.files || {});

  for (const [p, f] of files) {
    for (const dep of f.deps || []) {
      const a = L.pos.get(p), b = L.pos.get(dep);
      if (!a || !b) continue;
      const x1 = a.x + nodeW, y1 = a.y + nodeH / 2;
      const x2 = b.x, y2 = b.y + nodeH / 2;
      const mx = (x1 + x2) / 2;
      const pCyc = cycleMap.get(p);
      const depCyc = cycleMap.get(dep);
      let inCycle = false;
      if (pCyc && depCyc) {
        for (const cId of pCyc) {
          if (depCyc.has(cId)) {
            inCycle = true;
            break;
          }
        }
      }
      edges.push(
        `<path class="edge${inCycle ? " edge-cycle" : ""}" data-from="${esc(p)}" data-to="${esc(dep)}" d="M${x1},${y1} C${mx},${y1} ${mx},${y2} ${x2},${y2}" marker-end="url(#${inCycle ? "arrow-cycle" : "arrow"})"/>`
      );
    }
  }

  const nodes = [];
  for (const [p, f] of files) {
    const coords = L.pos.get(p);
    if (!coords) continue;
    const { x, y } = coords;
    const inCycle = cycleMap.has(p);
    const big = f.loc >= 600;
    const cls = inCycle ? "cyc" : big ? "big" : "nrm";
    const label = p.length > 27 ? "…" + p.slice(-26) : p;
    nodes.push(
      `<g class="node node-module ${cls}" tabindex="0" role="button" aria-label="Модуль ${esc(p)}" data-id="${esc(p)}" data-path="${esc(p)}" transform="translate(${x},${y})">` +
      `<rect width="${nodeW}" height="${nodeH}" rx="6"/>` +
      `<text class="nt" x="9" y="17">${esc(label)}</text>` +
      `<text class="nl" x="${nodeW - 9}" y="17" text-anchor="end">${f.loc} стр</text>` +
      `</g>`
    );
  }

  return `<svg id="graph" viewBox="0 0 ${L.width} ${L.height}">
  <defs>
    <marker id="arrow" markerWidth="9" markerHeight="9" refX="8" refY="3" orient="auto">
      <path d="M0,0 L0,6 L8,3 z" fill="#3b4557"/>
    </marker>
    <marker id="arrow-cycle" markerWidth="9" markerHeight="9" refX="8" refY="3" orient="auto">
      <path d="M0,0 L0,6 L8,3 z" fill="#f87171"/>
    </marker>
    <marker id="arrow-active" markerWidth="9" markerHeight="9" refX="8" refY="3" orient="auto">
      <path d="M0,0 L0,6 L8,3 z" fill="#60a5fa"/>
    </marker>
  </defs>
  <g id="viewport">
    <g id="edge-layer">${edges.join("\n    ")}</g>
    <g id="node-layer">${nodes.join("\n    ")}</g>
  </g>
</svg>`;
}

/** Embed safely into HTML */
function embedData(state, delta, findings) {
  const payload = {
    root: state.root || "",
    scannedAt: state.scannedAt || "",
    totals: state.totals || { files: 0, loc: 0, avgMi: 0 },
    cycles: state.cycles || [],
    files: {},
    symbols: state.symbols || [],
    calls: state.calls || [],
    unresolvedCalls: state.unresolvedCalls || [],
    analysis: state.analysis || {
      engine: "regex-heuristic",
      supportedExtensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"],
      limitations: ["Вызовы функций поддерживаются для JS/TS (.ts, .tsx, .js, .jsx, .mjs, .cjs)."],
      diagnostics: [],
    },
    delta: delta || null,
    findings: findings || { shown: [], suppressed: 0, total: 0 },
  };

  const jsTsExts = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

  for (const [p, f] of Object.entries(state.files || {})) {
    const extMatch = p.match(/\.[^.]+$/);
    const ext = extMatch ? extMatch[0].toLowerCase() : "";
    const isJsTs = jsTsExts.has(ext);

    payload.files[p] = {
      loc: f.loc || 0,
      complexity: f.complexity || 0,
      mi: f.mi || 0,
      fanIn: f.fanIn || 0,
      fanOut: f.fanOut || 0,
      deps: f.deps || [],
      members: (f.members || []).map((m) => ({
        name: m.name || m.n || "",
        kind: m.kind || m.k || "item",
        line: m.line || m.l || 1,
        heuristic: m.heuristic !== undefined ? m.heuristic : !isJsTs,
      })),
    };
  }

  return JSON.stringify(payload).replace(/</g, "\\u003c").replace(/>/g, "\\u003e");
}

/**
 * Main exported renderer function.
 * Must match: renderHtml(state, delta, findings): string
 */
export function renderHtml(state, delta, findings) {
  const safeState = state || { root: ".", scannedAt: new Date().toISOString(), files: {}, totals: { files: 0, loc: 0, avgMi: 0 }, cycles: [] };
  const safeDelta = delta || { first: true, added: [], removed: [], changed: [], newCycles: [], fixedCycles: [], scores: null };
  const safeFindings = findings || { shown: [], suppressed: 0, total: 0 };

  const supportedExtensions = (safeState.analysis && Array.isArray(safeState.analysis.supportedExtensions))
    ? safeState.analysis.supportedExtensions
    : [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts"];
  const supportedExtText = `TypeScript и JavaScript (${supportedExtensions.join(", ")})`;
  const score = safeState.totals ? safeState.totals.avgMi : 0;
  const band =
    score >= 75
      ? ["good", "#34d399", "высокая поддерживаемость"]
      : score >= 55
      ? ["fair", "#fbbf24", "умеренная сложность"]
      : ["poor", "#f87171", "высокий риск деградации"];

  const L = layoutModules(safeState);
  const initialSvg = renderModuleSvg(safeState, L);

  const shown = safeFindings.shown || [];
  const bySev = { high: [], medium: [], low: [] };
  for (const f of shown) (bySev[f.severity] || bySev.low).push(f);

  const findingCard = (f) => {
    const sevLabel = SEV_RU[f.severity] || f.severity || "инфо";
    const kindLabel = KIND_RU[f.kind] || f.kind || "замечание";
    const whatText = translateFindingText(f.what);
    const whyText = translateFindingText(f.why);
    const fixText = translateFindingText(f.fix);

    return `<div class="finding ${esc(f.severity || "low")}">
      <div class="fhead">
        <span class="sev ${esc(f.severity || "low")}">${esc(sevLabel)}</span>
        <span class="fkind">${esc(kindLabel)}</span>
        <strong>${esc(whatText)}</strong>
      </div>
      <div class="where">
        ${(f.where || []).map((w) => `<code class="flink" tabindex="0" role="button" aria-label="Открыть файл ${esc(w)}" data-path="${esc(w)}">${esc(w)}</code>`).join(" ")}
      </div>
      <p class="why">${esc(whyText)}</p>
      ${fixText ? `<p class="fix"><b>Рекомендация:</b> ${esc(fixText)}</p>` : ""}
    </div>`;
  };

  const deltaBlock = safeDelta.first
    ? `<p class="muted">Первый снимок репозитория — сравнительная динамика будет рассчитана при повторном анализе.</p>`
    : `<div class="grid">
        <div class="stat"><span>${safeDelta.scores && safeDelta.scores.files >= 0 ? "+" : ""}${safeDelta.scores ? safeDelta.scores.files : 0}</span><label>Файлы</label></div>
        <div class="stat"><span>${safeDelta.scores && safeDelta.scores.loc >= 0 ? "+" : ""}${safeDelta.scores ? safeDelta.scores.loc : 0}</span><label>Строки</label></div>
        <div class="stat ${(safeDelta.scores && safeDelta.scores.mi >= 0) ? "up" : "down"}"><span>${safeDelta.scores && safeDelta.scores.mi >= 0 ? "+" : ""}${safeDelta.scores ? safeDelta.scores.mi : 0}</span><label>Индекс MI</label></div>
      </div>
      ${safeDelta.added && safeDelta.added.length ? `<h3>Добавленные файлы (${safeDelta.added.length})</h3><ul class="files">${safeDelta.added.slice(0, 20).map((p) => `<li><code class="flink" tabindex="0" role="button" aria-label="Открыть файл ${esc(p)}" data-path="${esc(p)}">${esc(p)}</code></li>`).join("")}</ul>` : ""}
      ${safeDelta.removed && safeDelta.removed.length ? `<h3>Удалённые файлы (${safeDelta.removed.length})</h3><ul class="files">${safeDelta.removed.slice(0, 20).map((p) => `<li><code>${esc(p)}</code></li>`).join("")}</ul>` : ""}
      ${safeDelta.newCycles && safeDelta.newCycles.length ? `<h3 class="bad">Появились новые циклы (${safeDelta.newCycles.length})</h3><ul class="files">${safeDelta.newCycles.map((c) => `<li><code>${c.map(esc).join(" → ")}</code></li>`).join("")}</ul>` : ""}
      ${safeDelta.fixedCycles && safeDelta.fixedCycles.length ? `<h3 class="good">Устранены циклы (${safeDelta.fixedCycles.length})</h3><ul class="files">${safeDelta.fixedCycles.map((c) => `<li><code>${c.map(esc).join(" → ")}</code></li>`).join("")}</ul>` : ""}
      ${safeDelta.changed && safeDelta.changed.length ? `<h3>Изменённые файлы (${safeDelta.changed.length})</h3><table><tr><th>Файл</th><th>Строки</th><th>Ветвления</th><th>Индекс MI</th></tr>
        ${safeDelta.changed.sort((a, b) => Math.abs(b.loc) - Math.abs(a.loc)).slice(0, 25).map((c) =>
          `<tr><td><code class="flink" tabindex="0" role="button" aria-label="Открыть файл ${esc(c.path)}" data-path="${esc(c.path)}">${esc(c.path)}</code></td><td class="${c.loc > 0 ? "bad" : c.loc < 0 ? "good" : ""}">${c.loc >= 0 ? "+" : ""}${c.loc}</td><td>${c.cx >= 0 ? "+" : ""}${c.cx}</td><td class="${c.mi >= 0 ? "good" : "bad"}">${c.mi >= 0 ? "+" : ""}${c.mi}</td></tr>`).join("")}
      </table>` : ""}`;

  const topFiles = Object.entries(safeState.files || {})
    .sort((a, b) => (b[1].loc || 0) - (a[1].loc || 0))
    .slice(0, 15);

  const cycleList = safeState.cycles && safeState.cycles.length
    ? `<div class="cyclewarn">
        <b>Обнаружены циклы зависимостей (${safeState.cycles.length}):</b>
        <ul>${safeState.cycles.map((c) => `<li><code>${c.map(esc).join(" → ")}</code></li>`).join("")}</ul>
      </div>`
    : "";

  const totalSymbols = safeState.symbols ? safeState.symbols.length : 0;
  const totalCalls = safeState.calls ? safeState.calls.length : 0;
  const totalUnresolved = safeState.unresolvedCalls ? safeState.unresolvedCalls.length : 0;
  const analysisEngine = safeState.analysis && safeState.analysis.engine ? safeState.analysis.engine : "стандартный";

  return `<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Архитектурный отчёт — ${esc(String(safeState.root || "").split(/[\\/]/).pop() || "проект")}</title>
<style>
  :root {
    --bg: #0b0f17;
    --panel: #111622;
    --panel2: #171f30;
    --line: #232d42;
    --line-light: #33405a;
    --ink: #e2e8f0;
    --muted: #94a3b8;
    --dim: #64748b;
    --good: #34d399;
    --warn: #fbbf24;
    --bad: #f87171;
    --acc: #60a5fa;
    --acc-hover: #3b82f6;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html {
    box-sizing: border-box;
    max-width: 100vw;
    overflow-x: hidden;
  }
  body {
    background: var(--bg);
    color: var(--ink);
    font: 14px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    max-width: 100vw;
    overflow-x: hidden;
  }
  .wrap {
    max-width: 1300px;
    width: 100%;
    margin: 0 auto;
    padding: 32px 20px 80px;
    overflow-wrap: break-word;
    word-break: break-word;
  }
  header {
    margin-bottom: 24px;
    border-bottom: 1px solid var(--line);
    padding-bottom: 16px;
  }
  h1 {
    font-size: 26px;
    font-weight: 700;
    letter-spacing: -0.02em;
    color: #f8fafc;
    margin-bottom: 6px;
  }
  .sub {
    color: var(--muted);
    font-size: 13px;
  }
  h2 {
    font-size: 18px;
    font-weight: 600;
    margin: 36px 0 14px;
    color: #f1f5f9;
    letter-spacing: -0.01em;
    display: flex;
    align-items: center;
    gap: 8px;
  }
  h3 {
    font-size: 12px;
    margin: 18px 0 8px;
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 0.08em;
    font-weight: 600;
  }
  .card {
    background: var(--panel);
    border: 1px solid var(--line);
    border-radius: 12px;
    padding: 20px;
    margin: 14px 0;
    max-width: 100%;
    box-sizing: border-box;
  }
  .muted { color: var(--muted); }
  .good { color: var(--good); }
  .warn { color: var(--warn); }
  .bad { color: var(--bad); }
  code {
    font: 12px/1.4 ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    background: var(--panel2);
    color: #cbd5e1;
    padding: 2px 6px;
    border-radius: 4px;
    border: 1px solid rgba(255,255,255,0.05);
    word-break: break-all;
    overflow-wrap: break-word;
    max-width: 100%;
  }
  code.flink, code.jump {
    cursor: pointer;
    border-bottom: 1px dashed var(--dim);
    transition: color .15s, border-color .15s;
  }
  code.flink:hover, code.jump:hover {
    color: var(--acc);
    border-bottom-color: var(--acc);
  }
  code.flink:focus, code.jump:focus, .node:focus {
    outline: 2px solid var(--acc);
    outline-offset: 2px;
  }

  /* Health score card */
  .score-row {
    display: flex;
    align-items: baseline;
    gap: 16px;
    flex-wrap: wrap;
  }
  .score-num {
    font-size: 54px;
    font-weight: 800;
    line-height: 1;
    letter-spacing: -0.03em;
  }
  .score-meta {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .score-title {
    font-size: 15px;
    font-weight: 600;
    color: #f1f5f9;
  }
  .bar {
    height: 7px;
    background: var(--panel2);
    border-radius: 99px;
    margin: 16px 0 10px;
    overflow: hidden;
  }
  .bar > i {
    display: block;
    height: 100%;
    border-radius: 99px;
    transition: width .3s ease;
  }
  .score-desc {
    font-size: 12.5px;
    color: var(--dim);
  }

  /* Grid & stats */
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
    gap: 16px;
    margin: 10px 0;
    min-width: 0;
    max-width: 100%;
  }
  .stat {
    background: var(--panel2);
    border: 1px solid var(--line);
    border-radius: 8px;
    padding: 12px 14px;
    display: flex;
    flex-direction: column;
  }
  .stat span {
    font-size: 22px;
    font-weight: 700;
    color: #f8fafc;
    letter-spacing: -0.02em;
  }
  .stat label {
    font-size: 11px;
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 0.06em;
    margin-top: 4px;
  }
  .stat.up span { color: var(--good); }
  .stat.down span { color: var(--bad); }

  /* Graph controls & container */
  #graph-card {
    padding: 14px;
    position: relative;
    width: 100%;
    max-width: 100%;
    min-width: 0;
    box-sizing: border-box;
  }
  .graph-toolbar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
    margin-bottom: 12px;
    flex-wrap: wrap;
    width: 100%;
    max-width: 100%;
    min-width: 0;
    box-sizing: border-box;
  }
  .graph-controls {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
    flex: 1 1 auto;
    min-width: 0;
    max-width: 100%;
  }
  .graph-actions {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    flex-wrap: wrap;
    min-width: 0;
    max-width: 100%;
  }
  .btn-group {
    display: inline-flex;
    background: var(--panel2);
    border: 1px solid var(--line);
    border-radius: 7px;
    overflow: hidden;
    flex-shrink: 0;
    min-width: 0;
    max-width: 100%;
  }
  .btn-tab {
    background: transparent;
    border: none;
    color: var(--muted);
    padding: 6px 12px;
    font-size: 12px;
    font-weight: 500;
    cursor: pointer;
    transition: all .15s;
    white-space: nowrap;
  }
  .btn-tab:hover {
    color: var(--ink);
    background: rgba(255,255,255,0.03);
  }
  .btn-tab.active {
    background: var(--line);
    color: #ffffff;
    font-weight: 600;
  }
  .btn-action {
    background: var(--panel2);
    border: 1px solid var(--line);
    border-radius: 6px;
    color: var(--muted);
    padding: 5px 10px;
    font-size: 12px;
    cursor: pointer;
    transition: all .15s;
    white-space: nowrap;
    min-width: 0;
  }
  .btn-action:hover {
    color: var(--ink);
    border-color: var(--acc);
  }

  /* Search input */
  .search-box {
    position: relative;
    min-width: 240px;
    flex: 1 1 240px;
    max-width: 100%;
    box-sizing: border-box;
  }
  .search-input {
    width: 100%;
    background: var(--panel2);
    border: 1px solid var(--line);
    border-radius: 6px;
    color: var(--ink);
    padding: 6px 10px;
    font-size: 12.5px;
    outline: none;
    transition: border-color .15s;
  }
  .search-input:focus {
    border-color: var(--acc);
  }
  .search-results {
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    background: var(--panel);
    border: 1px solid var(--line);
    border-radius: 6px;
    max-height: 280px;
    overflow-y: auto;
    z-index: 30;
    display: none;
    box-shadow: 0 10px 24px rgba(0,0,0,0.5);
    margin-top: 4px;
  }
  .search-results.open {
    display: block;
  }
  .search-item {
    padding: 7px 10px;
    font-size: 12px;
    cursor: pointer;
    border-bottom: 1px solid rgba(255,255,255,0.04);
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .search-item:hover, .search-item:focus {
    background: var(--panel2);
    outline: none;
  }
  .search-item .tag {
    font-size: 10px;
    padding: 1px 5px;
    border-radius: 3px;
    background: var(--line);
    color: var(--muted);
  }

  /* Graph viewport */
  .graphwrap {
    position: relative;
    background: #0d121c;
    border: 1px solid var(--line);
    border-radius: 8px;
    overflow: hidden;
    width: 100%;
    max-width: 100%;
    min-width: 0;
    contain: inline-size;
    height: 560px;
    cursor: grab;
    box-sizing: border-box;
  }
  .graphwrap.grabbing {
    cursor: grabbing;
  }
  .graphwrap.fullscreen {
    position: fixed;
    inset: 0;
    width: 100vw !important;
    height: 100vh !important;
    z-index: 1000;
    border-radius: 0;
    border: none;
  }
  .fullscreen-exit {
    position: absolute;
    top: 16px;
    right: 16px;
    z-index: 1001;
    display: none;
    background: var(--panel);
    border: 1px solid var(--line);
    color: var(--ink);
    padding: 8px 14px;
    border-radius: 6px;
    font-size: 13px;
    cursor: pointer;
  }
  .graphwrap.fullscreen .fullscreen-exit {
    display: block;
  }

  svg#graph {
    display: block;
    user-select: none;
    width: 100% !important;
    max-width: none;
    height: 100% !important;
  }
  .node rect {
    fill: #161e2d;
    stroke: var(--line-light);
    stroke-width: 1;
    transition: fill .15s, stroke .15s, stroke-width .15s;
  }
  .node .nt {
    fill: #e2e8f0;
    font: 11px ui-monospace, SFMono-Regular, Menlo, monospace;
    pointer-events: none;
  }
  .node .nl {
    fill: var(--dim);
    font: 10px ui-monospace, monospace;
    pointer-events: none;
  }
  .node.big rect {
    fill: #261f10;
    stroke: #856417;
  }
  .node.cyc rect {
    fill: #2e1215;
    stroke: var(--bad);
  }
  .node.sel rect {
    fill: #192742;
    stroke: var(--acc);
    stroke-width: 2;
  }
  .node.neighbor rect {
    fill: #162438;
    stroke: var(--acc-hover);
    stroke-width: 1.5;
  }
  .node.dimmed {
    opacity: 0.22;
  }
  .node:hover rect {
    stroke: var(--acc);
  }
  .node {
    cursor: pointer;
  }

  .edge {
    fill: none;
    stroke: #33405a;
    stroke-width: 1.2;
    transition: stroke .15s, stroke-width .15s, opacity .15s;
  }
  .edge-cycle {
    stroke: var(--bad);
    stroke-width: 1.6;
  }
  .edge.active {
    stroke: var(--acc);
    stroke-width: 2;
  }
  .edge.dimmed {
    opacity: 0.12;
  }

  .legend {
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
    font-size: 12px;
    color: var(--muted);
    margin-top: 10px;
    align-items: center;
  }
  .sw {
    display: inline-block;
    width: 10px;
    height: 10px;
    border-radius: 2px;
    margin-right: 5px;
    vertical-align: -1px;
  }

  /* Findings list */
  .finding {
    border-left: 3px solid var(--line);
    padding: 12px 14px 12px 16px;
    margin: 12px 0;
    background: rgba(255,255,255,0.01);
    border-radius: 0 6px 6px 0;
  }
  .finding.high { border-color: var(--bad); }
  .finding.medium { border-color: var(--warn); }
  .finding.low { border-color: var(--dim); }
  .fhead {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
  }
  .sev {
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    padding: 2px 7px;
    border-radius: 99px;
    font-weight: 700;
  }
  .sev.high { background: #3b1418; color: #fca5a5; }
  .sev.medium { background: #3b2f12; color: #fcd34d; }
  .sev.low { background: #1e2634; color: #94a3b8; }
  .fkind {
    font-size: 11px;
    color: var(--muted);
  }
  .where { margin: 6px 0; }
  .why { margin: 6px 0 0; color: #cbd5e1; font-size: 13px; }
  .fix { margin: 6px 0 0; font-size: 13px; color: #93c5fd; }
  .cyclewarn {
    color: var(--warn);
    background: #231b0c;
    border: 1px solid #4d3a14;
    padding: 10px 14px;
    border-radius: 8px;
    margin: 10px 0;
    font-size: 13px;
  }
  .cyclewarn ul { margin: 6px 0 0 20px; }

  /* Tables */
  table {
    border-collapse: collapse;
    width: 100%;
    font-size: 13px;
    margin-top: 8px;
  }
  th, td {
    text-align: left;
    padding: 8px 10px;
    border-bottom: 1px solid var(--line);
  }
  th {
    color: var(--muted);
    font-weight: 600;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
  }
  tr:last-child td { border-bottom: none; }
  .files { margin: 6px 0; padding-left: 20px; }
  .files li { margin: 3px 0; }

  /* Detail drawer panel */
  #panel {
    position: fixed;
    top: 0;
    right: 0;
    height: 100vh;
    width: 440px;
    max-width: 100vw;
    box-sizing: border-box;
    border-left: 1px solid var(--line);
    transform: translateX(100%);
    transition: transform .22s ease-in-out;
    overflow-y: auto;
    padding: 24px 20px;
    box-shadow: -12px 0 36px rgba(0,0,0,0.6);
    z-index: 1100;
  }
  #panel.open { transform: translateX(0); }
  #close {
    position: absolute;
    top: 18px;
    right: 18px;
    background: var(--panel2);
    border: 1px solid var(--line);
    color: var(--muted);
    border-radius: 6px;
    padding: 4px 10px;
    font-size: 12px;
    cursor: pointer;
  }
  #close:hover { color: var(--ink); border-color: var(--acc); }
  .kv {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 5px 14px;
    font-size: 13px;
    margin: 12px 0;
    background: var(--panel2);
    padding: 10px 12px;
    border-radius: 6px;
  }
  .kv .k { color: var(--muted); }
  .kv .v { text-align: right; font-variant-numeric: tabular-nums; font-weight: 500; }
  .mem {
    display: grid;
    grid-template-columns: 46px 72px 1fr;
    gap: 6px 8px;
    font-size: 12px;
    padding: 5px 0;
    border-bottom: 1px solid rgba(255,255,255,0.04);
    align-items: center;
  }
  .mem .ln { color: var(--dim); text-align: right; font-family: ui-monospace, monospace; }
  .mem .kd { color: var(--dim); font-size: 10.5px; }
  .mem .nm { font-family: ui-monospace, monospace; color: #e2e8f0; word-break: break-all; }
  .plist {
    margin: 8px 0;
    padding: 0;
    list-style: none;
    font-size: 12.5px;
  }
  .plist li { padding: 3px 0; }
  .badge-h {
    font-size: 10px;
    padding: 1px 4px;
    background: rgba(251,191,36,0.15);
    color: #fbbf24;
    border-radius: 3px;
    margin-left: 6px;
    border: 1px solid rgba(251,191,36,0.3);
  }

  /* Unresolved calls table */
  .call-item {
    padding: 8px 10px;
    background: var(--panel2);
    border: 1px solid var(--line);
    border-radius: 6px;
    margin-bottom: 6px;
    font-size: 12.5px;
  }
  .call-expr {
    font-family: ui-monospace, monospace;
    color: #93c5fd;
    font-weight: 600;
  }
  .call-reason {
    font-size: 11px;
    color: var(--muted);
    margin-top: 3px;
  }

  footer {
    margin-top: 50px;
    color: var(--dim);
    font-size: 12px;
    border-top: 1px solid var(--line);
    padding-top: 16px;
  }

  @media (max-width: 768px) {
    .wrap {
      padding: 16px 12px 60px;
      width: 100%;
      max-width: 100vw;
      box-sizing: border-box;
    }
    #panel {
      width: 100vw;
      max-width: 100vw;
    }
    .graphwrap {
      height: 420px;
      width: 100%;
      max-width: 100%;
      min-width: 0;
      contain: inline-size;
    }
    .graph-toolbar {
      flex-direction: column;
      align-items: stretch;
      gap: 8px;
    }
    .graph-controls {
      width: 100%;
      flex-direction: column;
      align-items: stretch;
      gap: 8px;
    }
    .btn-group {
      width: 100%;
      display: flex;
    }
    .btn-tab {
      flex: 1 1 50%;
      text-align: center;
      padding: 7px 8px;
      font-size: 11.5px;
    }
    .graph-actions {
      width: 100%;
      display: flex;
      gap: 6px;
      justify-content: space-between;
    }
    .btn-action {
      flex: 1 1 auto;
      text-align: center;
      padding: 6px 8px;
      font-size: 11.5px;
    }
    .search-box {
      width: 100%;
      min-width: 100%;
    }
    .score-row {
      flex-direction: column;
      align-items: flex-start;
      gap: 8px;
    }
    table {
      display: block;
      overflow-x: auto;
      max-width: 100%;
      white-space: nowrap;
    }
  }
</style>
</head>
<body>
<div class="wrap">

<header>
  <h1>Архитектурный анализ</h1>
  <p class="sub">${esc(safeState.root || "")} · снимок от ${esc(String(safeState.scannedAt || "").replace("T", " ").slice(0, 16))}</p>
</header>

<div class="card">
  <div class="score-row">
    <div class="score-num" style="color:${band[1]}">${score}</div>
    <div class="score-meta">
      <div class="score-title">Индекс поддерживаемости (Maintainability Index, Microsoft MI)</div>
      <div class="muted">${band[2]} · ${safeState.totals.files} ${ruPlural(safeState.totals.files, "файл", "файла", "файлов")} · ${safeState.totals.loc.toLocaleString("ru-RU")} ${ruPlural(safeState.totals.loc, "строка", "строки", "строк")} кода</div>
    </div>
  <div class="bar"><i style="width:${Math.max(2, Math.min(100, score))}%;background:${band[1]}"></i></div>
  <p class="score-desc">Формула MI нормализована по шкале 0–100 на основе метрик Холстеда, цикломатической сложности Маккейба и физического объема строк кода. Отражает структурную сложность сопровождения.</p>
</div>

<h2>Граф архитектуры</h2>
<div class="card" id="graph-card">
  ${cycleList}
  <div class="graph-toolbar">
    <div class="graph-controls">
      <div class="btn-group" role="tablist">
        <button class="btn-tab active" id="tab-modules" role="tab" aria-selected="true">Модули (${safeState.totals.files})</button>
        <button class="btn-tab" id="tab-calls" role="tab" aria-selected="false">Вызовы функций (${totalCalls})</button>
      </div>
      <div class="graph-actions">
        <button class="btn-action" id="btn-connected-filter" style="display:none" title="Переключить показ изолированных символов">Все символы</button>
        <button class="btn-action" id="btn-fit" title="Центрировать и подогнать масштаб">Сбросить зум</button>
        <button class="btn-action" id="btn-fs" title="Развернуть на весь экран">Во весь экран</button>
      </div>
    </div>
    <div class="search-box">
      <input type="text" class="search-input" id="search-input" placeholder="Поиск модулей и функций..." autocomplete="off">
      <div class="search-results" id="search-results"></div>
    </div>
  </div>

  <div class="graphwrap" id="gw">
    <button class="fullscreen-exit" id="btn-exit-fs">✕ Свернуть</button>
    ${initialSvg}
  </div>

  <div class="legend" id="legend">
    <span><i class="sw" style="background:#161e2d;border:1px solid var(--line-light)"></i> Обычный модуль</span>
    <span><i class="sw" style="background:#261f10;border:1px solid #856417"></i> Крупный модуль (&ge;600 строк)</span>
    <span><i class="sw" style="background:#2e1215;border:1px solid var(--bad)"></i> Цикл взаимных зависимостей</span>
    <span class="muted" style="margin-left:auto;">Колёсико мыши: зум · Перетаскивание: панорама · Клик/Enter: карточка инспектора</span>
  </div>
</div>

<h2>Ограничения статического анализа и охват языков</h2>
<div class="card">
  <div class="kv" style="margin:0 0 12px 0">
    <span class="k">Движок анализа</span><span class="v">${esc(analysisEngine)}</span>
    <span class="k">Символы в проекте</span><span class="v">${totalSymbols}</span>
    <span class="k">Разрешённые вызовы</span><span class="v">${totalCalls}</span>
    <span class="k">Неразрешённые вызовы</span><span class="v">${totalUnresolved}</span>
  </div>
  <p class="muted" style="font-size:13px; margin-bottom:8px">
    Семантический граф вызовов формируется для ${esc(supportedExtText)}.
    Для остальных языков строится граф зависимостей модулей и эвристический обзор объявлений.
  </p>
  ${safeState.analysis && safeState.analysis.limitations && safeState.analysis.limitations.length
    ? `<ul class="files">${safeState.analysis.limitations.map((l) => `<li>${esc(translateFindingText(l))}</li>`).join("")}</ul>`
    : ""}

<h2>Изменения относительно предыдущего снимка</h2>
<div class="card">${deltaBlock}</div>

<h2>Замечания и архитектурные дефекты (${safeFindings.total || shown.length})</h2>
${shown.length
  ? `<div class="card">
      ${shown.map(findingCard).join("")}
      ${safeFindings.suppressed
        ? `<p class="muted" style="margin-top:16px;border-top:1px solid var(--line);padding-top:12px">
            И ещё ${safeFindings.suppressed} скрытых замечаний низкого приоритета.</p>`
        : ""}
    </div>`
  : `<div class="card"><p class="muted">Критических дефектов архитектуры не обнаружено.</p></div>`}

<h2>Крупнейшие файлы проекта</h2>
<div class="card">
  <table>
    <tr>
      <th>Файл</th>
      <th>Строки</th>
      <th>Ветвления</th>
      <th>Индекс MI</th>
      <th>Импортируют его</th>
    </tr>
    ${topFiles.map(([p, f]) => `<tr>
      <td><code class="flink" tabindex="0" role="button" aria-label="Открыть файл ${esc(p)}" data-path="${esc(p)}">${esc(p)}</code></td>
      <td>${f.loc}</td>
      <td>${f.complexity}</td>
      <td class="${f.mi >= 65 ? "good" : f.mi >= 40 ? "" : "bad"}">${f.mi}</td>
      <td>${f.fanIn}</td>
    </tr>`).join("")}
  </table>
</div>

<footer>
  Сгенерировано инструментарием archmap — статический офлайн-анализ без внешних облачных зависимостей.<br>
  ${safeFindings.total ? `Всего замечаний: ${bySev.high.length} важных · ${bySev.medium.length} средних · ${bySev.low.length} информационных.` : ""}
</footer>

</div>

<aside id="panel">
  <button id="close">✕ Закрыть</button>
  <div id="pc"></div>
</aside>

<script>
/* Embedded safe repository state */
const DATA = ${embedData(safeState, safeDelta, safeFindings)};

const KIND_RU = ${JSON.stringify(KIND_RU)};
const SYM_KIND_RU = ${JSON.stringify(SYM_KIND_RU)};
const REASON_RU = ${JSON.stringify(REASON_RU)};

/* Reverse dependency map */
const FILE_KEYS = Object.keys(DATA.files || {});
const USERS = {};
for (const p of FILE_KEYS) USERS[p] = [];
for (const p of FILE_KEYS) {
  for (const d of (DATA.files[p].deps || [])) {
    if (USERS[d]) USERS[d].push(p);
  }
}

/* Symbol maps */
const SYMBOLS_BY_ID = new Map();
const SYMBOLS_BY_FILE = new Map();
for (const s of (DATA.symbols || [])) {
  SYMBOLS_BY_ID.set(s.id, s);
  if (!SYMBOLS_BY_FILE.has(s.file)) SYMBOLS_BY_FILE.set(s.file, []);
  SYMBOLS_BY_FILE.get(s.file).push(s);
}

/* Call map: callers & callees */
const CALLERS_BY_SYM = new Map();
const CALLEES_BY_SYM = new Map();
for (const s of (DATA.symbols || [])) {
  CALLERS_BY_SYM.set(s.id, []);
  CALLEES_BY_SYM.set(s.id, []);
}
for (const c of (DATA.calls || [])) {
  if (CALLEES_BY_SYM.has(c.from)) CALLEES_BY_SYM.get(c.from).push(c);
  if (CALLERS_BY_SYM.has(c.to)) CALLERS_BY_SYM.get(c.to).push(c);
}

/* Unresolved calls by symbol or file */
const UNRESOLVED_BY_SYM = new Map();
const UNRESOLVED_BY_FILE = new Map();
for (const u of (DATA.unresolvedCalls || [])) {
  if (u.from) {
    if (!UNRESOLVED_BY_SYM.has(u.from)) UNRESOLVED_BY_SYM.set(u.from, []);
    UNRESOLVED_BY_SYM.get(u.from).push(u);
  }
  if (u.file) {
    if (!UNRESOLVED_BY_FILE.has(u.file)) UNRESOLVED_BY_FILE.set(u.file, []);
    UNRESOLVED_BY_FILE.get(u.file).push(u);
  }
}

/* DOM Elements */
const gw = document.getElementById("gw");
const svg = document.getElementById("graph");
const vp = document.getElementById("viewport");
const edgeLayer = document.getElementById("edge-layer");
const nodeLayer = document.getElementById("node-layer");
const panel = document.getElementById("panel");
const pc = document.getElementById("pc");
const tabModules = document.getElementById("tab-modules");
const tabCalls = document.getElementById("tab-calls");
const btnConnectedFilter = document.getElementById("btn-connected-filter");
const btnFit = document.getElementById("btn-fit");
const btnFs = document.getElementById("btn-fs");
const btnExitFs = document.getElementById("btn-exit-fs");
const searchInput = document.getElementById("search-input");
const searchResults = document.getElementById("search-results");

let currentMode = "modules"; // "modules" | "calls"
let callsFilterConnectedOnly = true;
let selectedId = null;
let selectedType = null; // "module" | "symbol"

/* Pan & Zoom State */
let scale = 1, tx = 0, ty = 0;
let dragging = false, moved = false, sx = 0, sy = 0;

function applyTransform() {
  vp.setAttribute("transform", "translate(" + tx + "," + ty + ") scale(" + scale + ")");
}

/* Fit whole graph within viewport */
function fitGraph() {
  if (!svg || !gw) return;
  const vb = svg.getAttribute("viewBox");
  if (!vb) return;
  const parts = vb.split(" ").map(Number);
  const w = parts[2] || 800;
  const h = parts[3] || 600;
  const gwW = gw.clientWidth || 800;
  const gwH = gw.clientHeight || 560;

  const k = Math.min(gwW / w, gwH / h, 1);
  scale = Math.max(0.04, k * 0.95);
  tx = (gwW - w * scale) / 2;
  ty = 16;
  applyTransform();
}

/* Focus and center viewport on a specific node */
function focusNode(id) {
  if (!svg || !gw || !id) return;
  const nodeEl = nodeLayer.querySelector('[data-id="' + CSS.escape(id) + '"]');
  if (!nodeEl) return;

  const tf = nodeEl.getAttribute("transform");
  if (!tf) return;
  const m = tf.match(/translate\(([^,]+),\s*([^)]+)\)/);
  if (!m) return;
  const nx = parseFloat(m[1]);
  const ny = parseFloat(m[2]);

  const rect = nodeEl.querySelector("rect");
  const nw = rect ? parseFloat(rect.getAttribute("width") || "200") : 200;
  const nh = rect ? parseFloat(rect.getAttribute("height") || "26") : 26;

  const gwW = gw.clientWidth || 800;
  const gwH = gw.clientHeight || 560;

  /* Keep current user scale if already readable (>= 0.75), else zoom in to 1.0 */
  if (scale < 0.75) {
    scale = 1.0;
  }
  tx = gwW / 2 - (nx + nw / 2) * scale;
  ty = gwH / 2 - (ny + nh / 2) * scale;
  applyTransform();
}

/* On resize/fullscreen transition, preserve selected focus or re-center */
function onViewportResize(oldW, oldH) {
  if (selectedId && nodeLayer.querySelector('[data-id="' + CSS.escape(selectedId) + '"]')) {
    focusNode(selectedId);
  } else if (oldW && oldH && gw.clientWidth && gw.clientHeight) {
    /* Scale tx/ty to track center shift without shrinking scale */
    const dw = (gw.clientWidth - oldW) / 2;
    const dh = (gw.clientHeight - oldH) / 2;
    tx += dw;
    ty += dh;
    applyTransform();
  } else {
    fitGraph();
  }
}
gw.addEventListener("wheel", (e) => {
  e.preventDefault();
  const r = gw.getBoundingClientRect();
  const mx = e.clientX - r.left, my = e.clientY - r.top;
  const k = e.deltaY < 0 ? 1.14 : 1 / 1.14;
  const ns = Math.min(4, Math.max(0.04, scale * k));
  tx = mx - (mx - tx) * (ns / scale);
  ty = my - (my - ty) * (ns / scale);
  scale = ns;
  applyTransform();
}, { passive: false });

gw.addEventListener("mousedown", (e) => {
  if (e.target.closest(".fullscreen-exit")) return;
  dragging = true;
  moved = false;
  sx = e.clientX - tx;
  sy = e.clientY - ty;
  gw.classList.add("grabbing");
});

window.addEventListener("mousemove", (e) => {
  if (!dragging) return;
  moved = true;
  tx = e.clientX - sx;
  ty = e.clientY - sy;
  applyTransform();
});

window.addEventListener("mouseup", () => {
  dragging = false;
  gw.classList.remove("grabbing");
});

/* Double-click safely invokes fitGraph */
gw.addEventListener("dblclick", (e) => {
  if (e.target.closest(".node")) return;
  fitGraph();
});

btnFit.addEventListener("click", fitGraph);

/* Fullscreen toggle */
function toggleFullscreen(force) {
  const isFs = typeof force === "boolean" ? force : !gw.classList.contains("fullscreen");
  const oldW = gw.clientWidth, oldH = gw.clientHeight;
  if (isFs) {
    gw.classList.add("fullscreen");
    btnFs.textContent = "Свернуть";
  } else {
    gw.classList.remove("fullscreen");
    btnFs.textContent = "Во весь экран";
  }
  /* Transition viewport smoothly: re-center on selection or adjust offset */
  setTimeout(() => onViewportResize(oldW, oldH), 30);
}

window.addEventListener("resize", () => {
  if (gw.classList.contains("fullscreen")) {
    onViewportResize();
  }
});
btnFs.addEventListener("click", () => toggleFullscreen());
btnExitFs.addEventListener("click", () => toggleFullscreen(false));

/* String escape helper for dynamic HTML */
function escHtml(str) {
  return String(str ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
  }[c]));
}

/* Switch Graph Mode */
function setMode(mode) {
  if (currentMode === mode && nodeLayer.children.length > 0) return;
  currentMode = mode;
  tabModules.classList.toggle("active", mode === "modules");
  tabModules.setAttribute("aria-selected", mode === "modules");
  tabCalls.classList.toggle("active", mode === "calls");
  tabCalls.setAttribute("aria-selected", mode === "calls");

  if (mode === "modules") {
    if (btnConnectedFilter) btnConnectedFilter.style.display = "none";
    renderModulesMode();
  } else {
    if (btnConnectedFilter) {
      btnConnectedFilter.style.display = "inline-block";
      btnConnectedFilter.textContent = callsFilterConnectedOnly ? "Все символы" : "Только связанные";
    }
    renderCallsMode();
  }
  closePanel();
  fitGraph();
}

tabModules.addEventListener("click", () => setMode("modules"));
tabCalls.addEventListener("click", () => setMode("calls"));
if (btnConnectedFilter) {
  btnConnectedFilter.addEventListener("click", () => {
    callsFilterConnectedOnly = !callsFilterConnectedOnly;
    btnConnectedFilter.textContent = callsFilterConnectedOnly ? "Все символы" : "Только связанные";
    renderCallsMode();
    if (selectedId && nodeLayer.querySelector('[data-id="' + CSS.escape(selectedId) + '"]')) {
      focusNode(selectedId);
    } else {
      fitGraph();
    }
  });
}

function renderModulesMode() {
  const files = Object.keys(DATA.files || {});
  const depth = new Map();
  const compute = (p, seen = new Set()) => {
    if (depth.has(p)) return depth.get(p);
    if (seen.has(p)) return 0;
    seen.add(p);
    const deps = (DATA.files[p] && DATA.files[p].deps) || [];
    const d = deps.length ? 1 + Math.max(0, ...deps.map((x) => compute(x, seen))) : 0;
    depth.set(p, d);
    return d;
  };
  for (const p of files) compute(p);

  const layers = new Map();
  for (const p of files) {
    const d = depth.get(p) || 0;
    if (!layers.has(d)) layers.set(d, []);
    layers.get(d).push(p);
  }
  const maxDepth = Math.max(0, ...[...layers.keys()]);
  const colW = 260, rowH = 42, padX = 40, padY = 50;
  const pos = new Map();
  let maxRows = 0;
  for (const [d, list] of layers) {
    list.sort();
    maxRows = Math.max(maxRows, list.length);
    list.forEach((p, i) => pos.set(p, { x: padX + (maxDepth - d) * colW, y: padY + i * rowH }));
  }
  const width = Math.max(700, padX * 2 + (maxDepth + 1) * colW);
  const height = Math.max(400, padY + maxRows * rowH + 60);
  svg.setAttribute("viewBox", "0 0 " + width + " " + height);
  svg.removeAttribute("width");
  svg.removeAttribute("height");

  const cycleMap = new Map();
  if (Array.isArray(DATA.cycles)) {
    DATA.cycles.forEach((comp, idx) => {
      if (!Array.isArray(comp)) return;
      for (const node of comp) {
        if (!cycleMap.has(node)) cycleMap.set(node, new Set());
        cycleMap.get(node).add(idx);
      }
    });
  }

  const nodeW = 200, nodeH = 26;
  const edgeHtml = [];

  for (const [p, f] of Object.entries(DATA.files || {})) {
    for (const dep of (f.deps || [])) {
      const a = pos.get(p), b = pos.get(dep);
      if (!a || !b) continue;
      const x1 = a.x + nodeW, y1 = a.y + nodeH / 2;
      const x2 = b.x, y2 = b.y + nodeH / 2;
      const mx = (x1 + x2) / 2;
      const pCyc = cycleMap.get(p);
      const depCyc = cycleMap.get(dep);
      let inCycle = false;
      if (pCyc && depCyc) {
        for (const cId of pCyc) {
          if (depCyc.has(cId)) {
            inCycle = true;
            break;
          }
        }
      }
      edgeHtml.push(
        '<path class="edge' + (inCycle ? " edge-cycle" : "") + '" data-from="' + escHtml(p) + '" data-to="' + escHtml(dep) + '" d="M' + x1 + ',' + y1 + ' C' + mx + ',' + y1 + ' ' + mx + ',' + y2 + ' ' + x2 + ',' + y2 + '" marker-end="url(#' + (inCycle ? "arrow-cycle" : "arrow") + ')"/>'
      );
    }
  }

  const nodeHtml = [];
  for (const [p, f] of Object.entries(DATA.files || {})) {
    const coords = pos.get(p);
    if (!coords) continue;
    const { x, y } = coords;
    const inCycle = cycleMap.has(p);
    const big = (f.loc || 0) >= 600;
    const cls = inCycle ? "cyc" : big ? "big" : "nrm";
    const label = p.length > 27 ? "…" + p.slice(-26) : p;
    nodeHtml.push(
      '<g class="node node-module ' + cls + '" tabindex="0" role="button" aria-label="Модуль ' + escHtml(p) + '" data-id="' + escHtml(p) + '" data-path="' + escHtml(p) + '" transform="translate(' + x + ',' + y + ')">' +
      '<rect width="' + nodeW + '" height="' + nodeH + '" rx="6"/>' +
      '<text class="nt" x="9" y="17">' + escHtml(label) + '</text>' +
      '<text class="nl" x="' + (nodeW - 9) + '" y="17" text-anchor="end">' + (f.loc || 0) + ' стр</text>' +
      '</g>'
    );
  }

  edgeLayer.innerHTML = edgeHtml.join("\\n");
  nodeLayer.innerHTML = nodeHtml.join("\\n");
}

function renderCallsMode() {
  const allSymbols = DATA.symbols || [];
  const calls = DATA.calls || [];

  if (!allSymbols.length) {
    svg.setAttribute("viewBox", "0 0 800 300");
    edgeLayer.innerHTML = "";
    nodeLayer.innerHTML =
      '<g transform="translate(40, 100)">' +
      '<text fill="#94a3b8" font-size="14">Семантический граф вызовов доступен для JS/TS (.ts, .tsx, .js, .jsx, .mjs, .cjs).</text>' +
      '<text fill="#64748b" font-size="12" y="30">Символы не обнаружены или в проекте отсутствуют вызовы между функциями.</text>' +
      '</g>';
    return;
  }

  const allSymMap = new Map();
  for (const s of allSymbols) allSymMap.set(s.id, s);

  /* Determine connected symbols */
  const connectedIds = new Set();
  for (const c of calls) {
    if (allSymMap.has(c.from) && allSymMap.has(c.to)) {
      connectedIds.add(c.from);
      connectedIds.add(c.to);
    }
  }

  /* Filter symbols according to toggle */
  const displaySymbols = (callsFilterConnectedOnly && connectedIds.size > 0)
    ? allSymbols.filter((s) => connectedIds.has(s.id))
    : allSymbols;

  const symMap = new Map();
  for (const s of displaySymbols) symMap.set(s.id, s);

  const adj = new Map();
  for (const s of displaySymbols) adj.set(s.id, []);
  for (const c of calls) {
    if (symMap.has(c.from) && symMap.has(c.to)) {
      adj.get(c.from).push(c.to);
    }
  }

  const depth = new Map();
  const computeDepth = (id, seen = new Set()) => {
    if (depth.has(id)) return depth.get(id);
    if (seen.has(id)) return 0;
    seen.add(id);
    const neighbors = adj.get(id) || [];
    const d = neighbors.length ? 1 + Math.max(0, ...neighbors.map((n) => computeDepth(n, seen))) : 0;
    depth.set(id, d);
    return d;
  };
  for (const s of displaySymbols) computeDepth(s.id);

  const layers = new Map();
  for (const s of displaySymbols) {
    const d = depth.get(s.id) || 0;
    if (!layers.has(d)) layers.set(d, []);
    layers.get(d).push(s);
  }
  const maxDepth = Math.max(0, ...[...layers.keys()]);
  const colW = 280, rowH = 44, padX = 40, padY = 50;
  const pos = new Map();
  const maxLayerRows = 24;
  let maxVirtualRows = 0;
  let currentColOffset = 0;

  for (let d = maxDepth; d >= 0; d--) {
    const list = layers.get(d) || [];
    list.sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line);
    const numSubCols = Math.max(1, Math.ceil(list.length / maxLayerRows));
    const effectiveRows = Math.min(list.length, maxLayerRows);
    maxVirtualRows = Math.max(maxVirtualRows, effectiveRows);
    list.forEach((s, i) => {
      const subCol = Math.floor(i / maxLayerRows);
      const subRow = i % maxLayerRows;
      pos.set(s.id, {
        x: padX + (currentColOffset + subCol) * colW,
        y: padY + subRow * rowH,
      });
    });
    currentColOffset += numSubCols;
  }

  const width = Math.max(700, padX * 2 + currentColOffset * colW);
  const height = Math.max(400, padY + maxVirtualRows * rowH + 60);
  svg.setAttribute("viewBox", "0 0 " + width + " " + height);
  svg.removeAttribute("width");
  svg.removeAttribute("height");

  const nodeW = 220, nodeH = 28;
  const edgeHtml = [];

  for (const c of calls) {
    const a = pos.get(c.from), b = pos.get(c.to);
    if (!a || !b) continue;
    const x1 = a.x + nodeW, y1 = a.y + nodeH / 2;
    const x2 = b.x, y2 = b.y + nodeH / 2;
    const mx = (x1 + x2) / 2;
    edgeHtml.push(
      '<path class="edge" data-from="' + escHtml(c.from) + '" data-to="' + escHtml(c.to) + '" d="M' + x1 + ',' + y1 + ' C' + mx + ',' + y1 + ' ' + mx + ',' + y2 + ' ' + x2 + ',' + y2 + '" marker-end="url(#arrow)"/>'
    );
  }

  const nodeHtml = [];
  for (const s of displaySymbols) {
    const coords = pos.get(s.id);
    if (!coords) continue;
    const { x, y } = coords;
    const kindRu = SYM_KIND_RU[s.kind] || s.kind;
    const shortFile = s.file.split(/[\\\\/]/).pop();
    const label = s.name + " (" + shortFile + ":" + s.line + ")";
    const displayLabel = label.length > 30 ? "…" + label.slice(-29) : label;

    nodeHtml.push(
      '<g class="node node-symbol nrm" tabindex="0" role="button" aria-label="' + escHtml(kindRu) + ' ' + escHtml(s.name) + '" data-id="' + escHtml(s.id) + '" data-file="' + escHtml(s.file) + '" transform="translate(' + x + ',' + y + ')">' +
      '<rect width="' + nodeW + '" height="' + nodeH + '" rx="6"/>' +
      '<text class="nt" x="9" y="18">' + escHtml(displayLabel) + '</text>' +
      '<text class="nl" x="' + (nodeW - 9) + '" y="18" text-anchor="end">' + escHtml(kindRu) + '</text>' +
      '</g>'
    );
  }

  edgeLayer.innerHTML = edgeHtml.join("\\n");
  nodeLayer.innerHTML = nodeHtml.join("\\n");
}

/* Neighbor Highlighting */
function highlightNeighbors(id) {
  const allNodes = nodeLayer.querySelectorAll(".node");
  const allEdges = edgeLayer.querySelectorAll(".edge");

  if (!id) {
    allNodes.forEach((n) => { n.classList.remove("sel", "neighbor", "dimmed"); });
    allEdges.forEach((e) => { e.classList.remove("active", "dimmed"); });
    return;
  }

  const activeNeighbors = new Set([id]);

  allEdges.forEach((e) => {
    const from = e.getAttribute("data-from");
    const to = e.getAttribute("data-to");
    if (from === id || to === id) {
      e.classList.add("active");
      e.classList.remove("dimmed");
      if (from) activeNeighbors.add(from);
      if (to) activeNeighbors.add(to);
    } else {
      e.classList.remove("active");
      e.classList.add("dimmed");
    }
  });

  allNodes.forEach((n) => {
    const nid = n.getAttribute("data-id");
    if (nid === id) {
      n.classList.add("sel");
      n.classList.remove("neighbor", "dimmed");
    } else if (activeNeighbors.has(nid)) {
      n.classList.add("neighbor");
      n.classList.remove("sel", "dimmed");
    } else {
      n.classList.remove("sel", "neighbor");
      n.classList.add("dimmed");
    }
  });
}

/* Inspect module */
function selectModule(path) {
  if (!DATA.files[path]) return;
  if (currentMode !== "modules") {
    setMode("modules");
  }
  selectedId = path;
  selectedType = "module";
  highlightNeighbors(path);
  focusNode(path);

  const f = DATA.files[path];
  const deps = (f.deps || []).map((d) =>
    '<li><code class="jump" tabindex="0" role="button" aria-label="Открыть модуль ' + escHtml(d) + '" data-target="' + escHtml(d) + '" data-type="module">' + escHtml(d) + '</code></li>'
  ).join("") || '<li class="muted">—</li>';

  const users = (USERS[path] || []).map((u) =>
    '<li><code class="jump" tabindex="0" role="button" aria-label="Открыть модуль ' + escHtml(u) + '" data-target="' + escHtml(u) + '" data-type="module">' + escHtml(u) + '</code></li>'
  ).join("") || '<li class="muted">—</li>';

  const syms = SYMBOLS_BY_FILE.get(path) || [];
  const symHtml = syms.length
    ? syms.map((s) =>
        '<div class="mem">' +
          '<span class="ln">' + s.line + '</span>' +
          '<span class="kd">' + escHtml(SYM_KIND_RU[s.kind] || s.kind) + '</span>' +
          '<span class="nm"><code class="jump" tabindex="0" role="button" aria-label="Выбрать символ ' + escHtml(s.name) + '" data-target="' + escHtml(s.id) + '" data-type="symbol">' + escHtml(s.name) + '</code></span>' +
        '</div>'
      ).join("")
    : (f.members || []).map((m) =>
        '<div class="mem">' +
          '<span class="ln">' + m.line + '</span>' +
          '<span class="kd">' + escHtml(SYM_KIND_RU[m.kind] || m.kind) + (m.heuristic ? '<span class="badge-h">эвристика</span>' : '') + '</span>' +
          '<span class="nm">' + escHtml(m.name) + '</span>' +
        '</div>'
      ).join("") || '<p class="muted">Объявления не найдены</p>';

  const unres = UNRESOLVED_BY_FILE.get(path) || [];
  const unresHtml = unres.length
    ? unres.map((u) =>
        '<div class="call-item">' +
          '<div class="call-expr">стр. ' + u.line + ': ' + escHtml(u.expression) + '</div>' +
          '<div class="call-reason">' + escHtml(REASON_RU[u.reason] || u.reason) + '</div>' +
        '</div>'
      ).join("")
    : '<p class="muted">Неразрешённых вызовов нет</p>';

  pc.innerHTML =
    '<h3>Модуль</h3>' +
    '<p><code>' + escHtml(path) + '</code></p>' +
    '<div class="kv">' +
      '<span class="k">Строк кода</span><span class="v">' + f.loc + '</span>' +
      '<span class="k">Сложность (ветвления)</span><span class="v">' + f.complexity + '</span>' +
      '<span class="k">Индекс MI</span><span class="v">' + f.mi + ' / 100</span>' +
      '<span class="k">Входящие зависимости</span><span class="v">' + f.fanIn + '</span>' +
      '<span class="k">Исходящие зависимости</span><span class="v">' + f.fanOut + '</span>' +
    '</div>' +
    '<h3>Объявления и функции (' + (syms.length || f.members.length) + ')</h3>' +
    symHtml +
    '<h3>Импортирует модули (' + (f.deps || []).length + ')</h3>' +
    '<ul class="plist">' + deps + '</ul>' +
    '<h3>Импортируется модулями (' + (USERS[path] || []).length + ')</h3>' +
    '<ul class="plist">' + users + '</ul>' +
    '<h3>Неразрешённые вызовы (' + unres.length + ')</h3>' +
    unresHtml;

  bindJumps();
  panel.classList.add("open");
}

/* Inspect symbol */
function selectSymbol(id) {
  const s = SYMBOLS_BY_ID.get(id);
  if (!s) return;
  if (currentMode !== "calls") {
    setMode("calls");
  }
  /* If symbol node is not in current DOM (e.g. isolated and filter is active), ensure it is visible */
  if (!nodeLayer.querySelector('[data-id="' + CSS.escape(id) + '"]')) {
    if (callsFilterConnectedOnly) {
      callsFilterConnectedOnly = false;
      if (btnConnectedFilter) btnConnectedFilter.textContent = "Только связанные";
      renderCallsMode();
    }
  }
  selectedId = id;
  selectedType = "symbol";
  highlightNeighbors(id);
  focusNode(id);

  const callers = CALLERS_BY_SYM.get(id) || [];
  const callees = CALLEES_BY_SYM.get(id) || [];
  const unres = UNRESOLVED_BY_SYM.get(id) || [];

  const callersHtml = callers.length
    ? callers.map((c) => {
        const callerSym = SYMBOLS_BY_ID.get(c.from);
        const name = callerSym ? callerSym.name : c.from;
        return '<li><code class="jump" tabindex="0" role="button" aria-label="Выбрать символ ' + escHtml(name) + '" data-target="' + escHtml(c.from) + '" data-type="symbol">' + escHtml(name) + '</code> <span class="muted">(стр. ' + c.line + ')</span></li>';
      }).join("")
    : '<li class="muted">Прямых вызовов не обнаружено</li>';

  const calleesHtml = callees.length
    ? callees.map((c) => {
        const calleeSym = SYMBOLS_BY_ID.get(c.to);
        const name = calleeSym ? calleeSym.name : c.to;
        return '<li><code class="jump" tabindex="0" role="button" aria-label="Выбрать символ ' + escHtml(name) + '" data-target="' + escHtml(c.to) + '" data-type="symbol">' + escHtml(name) + '</code> <span class="muted">(стр. ' + c.line + ')</span></li>';
      }).join("")
    : '<li class="muted">Не вызывает другие известные символы</li>';

  const unresHtml = unres.length
    ? unres.map((u) =>
        '<div class="call-item">' +
          '<div class="call-expr">' + escHtml(u.expression) + ' (стр. ' + u.line + ')</div>' +
          '<div class="call-reason">' + escHtml(REASON_RU[u.reason] || u.reason) + '</div>' +
        '</div>'
      ).join("")
    : '<p class="muted">Все вызовы внутри функции разрешены</p>';

  pc.innerHTML =
    '<h3>Символ (функция / метод)</h3>' +
    '<p><strong style="font-size:16px;color:#f8fafc">' + escHtml(s.name) + '</strong> <span class="muted">(' + escHtml(SYM_KIND_RU[s.kind] || s.kind) + ')</span></p>' +
    '<p style="margin-top:4px"><code class="jump" tabindex="0" role="button" aria-label="Открыть модуль ' + escHtml(s.file) + '" data-target="' + escHtml(s.file) + '" data-type="module">' + escHtml(s.file) + ':' + s.line + '-' + s.endLine + '</code></p>' +
    '<div class="kv">' +
      '<span class="k">Строки в файле</span><span class="v">' + s.line + '–' + s.endLine + ' (' + (s.endLine - s.line + 1) + ' стр)</span>' +
      '<span class="k">Входящих вызовов</span><span class="v">' + callers.length + '</span>' +
      '<span class="k">Исходящих вызовов</span><span class="v">' + callees.length + '</span>' +
    '</div>' +
    '<h3>Кто вызывает (' + callers.length + ')</h3>' +
    '<ul class="plist">' + callersHtml + '</ul>' +
    '<h3>Кого вызывает (' + callees.length + ')</h3>' +
    '<ul class="plist">' + calleesHtml + '</ul>' +
    '<h3>Неразрешённые вызовы (' + unres.length + ')</h3>' +
    unresHtml;

  bindJumps();
  panel.classList.add("open");
}

function closePanel() {
  panel.classList.remove("open");
  selectedId = null;
  selectedType = null;
  highlightNeighbors(null);
}

document.getElementById("close").addEventListener("click", closePanel);

function handleJumpAction(el) {
  const target = el.getAttribute("data-target");
  const type = el.getAttribute("data-type");
  if (type === "module") selectModule(target);
  else if (type === "symbol") selectSymbol(target);
}

function bindJumps() {
  pc.querySelectorAll(".jump").forEach((el) => {
    el.addEventListener("click", () => handleJumpAction(el));
    el.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        handleJumpAction(el);
      }
    });
  });
}

function handleNodeAction(g) {
  const id = g.getAttribute("data-id");
  if (g.classList.contains("node-module")) {
    selectModule(id);
  } else if (g.classList.contains("node-symbol")) {
    selectSymbol(id);
  }
}

/* Node click and keyboard handlers */
svg.addEventListener("click", (e) => {
  if (moved) return;
  const g = e.target.closest(".node");
  if (!g) return;
  handleNodeAction(g);
});

svg.addEventListener("keydown", (e) => {
  if (e.key === "Enter" || e.key === " ") {
    const g = e.target.closest(".node");
    if (!g) return;
    e.preventDefault();
    handleNodeAction(g);
  }
});

/* Keyboard shortcuts */
document.addEventListener("keydown", (e) => {
  if (e.key === "Escape") {
    if (gw.classList.contains("fullscreen")) {
      toggleFullscreen(false);
    } else if (panel.classList.contains("open")) {
      closePanel();
    } else {
      searchResults.classList.remove("open");
      highlightNeighbors(null);
    }
  }
});

/* Search interaction: show all matches in scrollable container */
searchInput.addEventListener("input", (e) => {
  const query = e.target.value.trim().toLowerCase();
  if (!query) {
    searchResults.classList.remove("open");
    searchResults.innerHTML = "";
    return;
  }

  const matched = [];

  // Search all modules
  for (const p of FILE_KEYS) {
    if (p.toLowerCase().includes(query)) {
      matched.push({ id: p, name: p, type: "module", tag: "модуль" });
    }
  }

  // Search all symbols
  for (const s of (DATA.symbols || [])) {
    if (s.name.toLowerCase().includes(query) || s.file.toLowerCase().includes(query)) {
      matched.push({ id: s.id, name: s.name + " (" + s.file + ":" + s.line + ")", type: "symbol", tag: SYM_KIND_RU[s.kind] || s.kind });
    }
  }

  if (!matched.length) {
    searchResults.innerHTML = '<div class="search-item muted">Ничего не найдено</div>';
    searchResults.classList.add("open");
    return;
  }

  searchResults.innerHTML = matched.map((m) =>
    '<div class="search-item" tabindex="0" role="button" aria-label="' + escHtml(m.tag) + ' ' + escHtml(m.name) + '" data-id="' + escHtml(m.id) + '" data-type="' + escHtml(m.type) + '">' +
      '<span>' + escHtml(m.name) + '</span>' +
      '<span class="tag">' + escHtml(m.tag) + '</span>' +
    '</div>'
  ).join("");
  searchResults.classList.add("open");

  searchResults.querySelectorAll(".search-item").forEach((item) => {
    const selectItem = () => {
      const id = item.getAttribute("data-id");
      const type = item.getAttribute("data-type");
      searchResults.classList.remove("open");
      if (type === "module") selectModule(id);
      else if (type === "symbol") selectSymbol(id);
    };
    item.addEventListener("click", selectItem);
    item.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        selectItem();
      }
    });
  });
});

document.addEventListener("click", (e) => {
  if (!e.target.closest(".search-box")) {
    searchResults.classList.remove("open");
  }
});

/* Bind external file links */
document.querySelectorAll(".flink").forEach((el) => {
  const openLink = () => {
    const path = el.getAttribute("data-path");
    if (path) selectModule(path);
  };
  el.addEventListener("click", openLink);
  el.addEventListener("keydown", (e) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      openLink();
    }
  });
});

/* Initial center */
fitGraph();
</script>
</body>
</html>`;
}
